# Generated by Django 5.0.4 on 2024-05-03 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=64, verbose_name='Фамилия')),
                ('age', models.IntegerField(verbose_name='Возраст')),
                ('job', models.CharField(max_length=64, verbose_name='Должность')),
            ],
        ),
    ]
