# Generated by Django 5.0.4 on 2024-05-03 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ulearn', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name': 'Человек', 'verbose_name_plural': 'Люди'},
        ),
    ]
